deploy_develop:
  stage: deploy
  script:
    - hostnamectl
    - ssh -p 4443 fitness@79.137.127.154 "cd /home/fitness/websites/fitness &&
        git checkout develop -f &&
        git fetch &&
        git checkout $CI_COMMIT_SHA "

  only:
    - develop
